// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIpWQGu_pLcigS2ekYFY4npYhYls8t6IE',
    appId: '1:76682411676:web:24096396566d06317f3759',
    messagingSenderId: '76682411676',
    projectId: 'lvmmm-68263',
    authDomain: 'lvmmm-68263.firebaseapp.com',
    storageBucket: 'lvmmm-68263.firebasestorage.app',
    measurementId: 'G-J6TSNLXG96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACXk_Leo_Wm2Ssy3BY1b2wiw5WDqzbJY8',
    appId: '1:76682411676:android:26e4de54c3ab471a7f3759',
    messagingSenderId: '76682411676',
    projectId: 'lvmmm-68263',
    storageBucket: 'lvmmm-68263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIousdtFRr9587ul9NwaHgcbsymzOPRhg',
    appId: '1:76682411676:ios:49c9b80c4ac3dbc47f3759',
    messagingSenderId: '76682411676',
    projectId: 'lvmmm-68263',
    storageBucket: 'lvmmm-68263.firebasestorage.app',
    iosBundleId: 'com.example.lvt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIousdtFRr9587ul9NwaHgcbsymzOPRhg',
    appId: '1:76682411676:ios:49c9b80c4ac3dbc47f3759',
    messagingSenderId: '76682411676',
    projectId: 'lvmmm-68263',
    storageBucket: 'lvmmm-68263.firebasestorage.app',
    iosBundleId: 'com.example.lvt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIpWQGu_pLcigS2ekYFY4npYhYls8t6IE',
    appId: '1:76682411676:web:0fb607b98aa5f5607f3759',
    messagingSenderId: '76682411676',
    projectId: 'lvmmm-68263',
    authDomain: 'lvmmm-68263.firebaseapp.com',
    storageBucket: 'lvmmm-68263.firebasestorage.app',
    measurementId: 'G-LJDBGJ7KXB',
  );
}
